### ISSUE TITLE
Your both lib has same package name.

### ISSUE THREAD

**Issue by atulgoswami21** [DevLight-Mobile-Agency/NavigationTabStrip#1]
i am already using your 'com.github.devlight.navigationtabbar:library:1.1.6' and today when i included your this library the below error pop out. Please do need full changes.

Error:Execution failed for task ':app:processDebugResources'.

> Error: more than one library with package name 'com.gigamole.library'

**Comment by GIGAMOLE** [comment]
Hello. Sorry. Wait for update. Miss this moment.

**Comment by GIGAMOLE** [comment]
Update 1.0.1 is on the rails.
