### ISSUE TITLE
Android Studio Can't find the library

### ISSUE THREAD

**Issue by HosseinLamei** [DevLight-Mobile-Agency/NavigationTabStrip#10]
Hi , Thank you for this **beutiful** library but , when i try to add it to my project **Android Studio** Can't find it What shoud i do ?

**Comment by GIGAMOLE** [comment]
Hello. Yes, i know. This is the bintray linking. Wait for fix.

**Comment by GIGAMOLE** [comment]
Fixed.

**Comment by HosseinLamei** [comment]
But now like before android studio can't find it .

**Comment by GIGAMOLE** [comment]
Try to clear cache or check valid compile path. I have tried last version to compile and there are no errors.
