### ISSUE TITLE
Fragments

### ISSUE THREAD

**Issue by ghost** [DevLight-Mobile-Agency/NavigationTabStrip#11]
Hi, Thanks for the library. It looks and works fantastic. One question, though. How can I attach different fragments to different tabs?
Thanks.

**Comment by GIGAMOLE** [comment]
Hello. Thanks a lot. Just use method setViewPager() and use the FragmentPagerAdapter on it.

**Comment by MarkOSullivan94** [comment]
@GIGAMOLE do you have a working example of this?

**Comment by GIGAMOLE** [comment]
Look at the sample. There are ViewPager. Or look at the sample of another my library: https://github.com/DevLight-Mobile-Agency/InfiniteCycleViewPager.
