### ISSUE TITLE
setOnTabStripSelectedIndexListener Sample

### ISSUE THREAD

**Issue by shahbazly** [DevLight-Mobile-Agency/NavigationTabStrip#13]
Hi! Please, can you show an example of setOnTabStripSelectedIndexListener?
Unfortunately, I can't understand how it works :(

**Comment by GIGAMOLE** [comment]
Hello. Thanks.
Sure. You welcome:

navigationTabStrip.setOnTabStripSelectedIndexListener(new NavigationTabStrip.OnTabStripSelectedIndexListener() {
            @Override
            public void onStartTabSelected(final String title, final int index) {
// Trigger when you click on tab, seems like onClick()
            }

```
        @Override
        public void onEndTabSelected(final String title, final int index) {
```

// Trigger when strip finish move and select index
            }
        });
