### ISSUE TITLE
How to make same effect?

### ISSUE THREAD

**Issue by shahbazly** [DevLight-Mobile-Agency/NavigationTabStrip#14]
Здравствуйте! Спасибо вам за эту прекрасную библиотеку!:) Можете пожалуйста подсказать(желательно кодом) как сделать такой же эффект при листании?

Hello! Thank you for this great library! :) Can you please suggest (preferably code) how to make the same effect when scrolling?
![123](https://cloud.githubusercontent.com/assets/8513082/16899452/b2e5714c-4c0c-11e6-9c68-d725d9514f54.gif)

**Comment by GIGAMOLE** [comment]
Привет. Спасибо за ваш отзыв. Библиотека уже может делать такой еффект. Вы можете попробовать листать средний NTS в семпл аппе. Если вы хотите использовать эту библиотеку с ViewPager просто используйте метод navigationTabStrip.setViewPager();
