### ISSUE TITLE
Title new line

### ISSUE THREAD

**Issue by oZBo** [DevLight-Mobile-Agency/NavigationTabStrip#15]
Hi! Thanks for providing such a good library!
I have a question: is there possibility to add new line to the TabTitle? I set text with "\n" but it drawing like single line. 
Thanks in advance!

**Comment by GIGAMOLE** [comment]
Hello. Thanks for feedback. Unfortunately, this feature is unavailable because it is inconsistent guidelines of design.

**Comment by GIGAMOLE** [comment]
Just try to set short titles like google recommends.

**Comment by Eeram** [comment]
Hi,

Thanks for this very sweet lib! It's quite unfortunate that the `\n` doesn't work though.

Assuming I'd like to have a long title anyway and to put it on two lines, could you give me a hint on what I should change in your lib to make it work?

Thank you!

**Comment by GIGAMOLE** [comment]
Hello. Thanks for this question. 
No. Its impossible. Google design guidelines doesnt recommend to use multiline in navigation bars, so there is the result. 

Yes. You can get this effect in next way: 
Just modify onDraw() where the title are drawn and split title by \n and then draw it.
