### ISSUE TITLE
Asset not found:null Error

### ISSUE THREAD

**Issue by Adarshjain** [DevLight-Mobile-Agency/NavigationTabStrip#16]
In my xml file it says 
Rendering problem 
Asset not found : null
what should i do?

during runtime it logcats this exception

08-07 01:49:38.304 25153-25153/? W/System.err: java.lang.NullPointerException
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.graphics.FontFamily.nAddFontFromAsset(Native Method)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.graphics.FontFamily.addFontFromAsset(FontFamily.java:70)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.graphics.Typeface.createFromAsset(Typeface.java:185)
08-07 01:49:38.304 25153-25153/? W/System.err:     at com.gigamole.navigationtabstrip.NavigationTabStrip.setTypeface(NavigationTabStrip.java:343)
08-07 01:49:38.304 25153-25153/? W/System.err:     at com.gigamole.navigationtabstrip.NavigationTabStrip.<init>(NavigationTabStrip.java:189)
08-07 01:49:38.304 25153-25153/? W/System.err:     at com.gigamole.navigationtabstrip.NavigationTabStrip.<init>(NavigationTabStrip.java:156)
08-07 01:49:38.304 25153-25153/? W/System.err:     at java.lang.reflect.Constructor.newInstance(Native Method)
08-07 01:49:38.304 25153-25153/? W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:611)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:810)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:508)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:418)
08-07 01:49:38.304 25153-25153/? W/System.err:     at com.geeky.adarsh.moviescollection.Fragments.MainFragment.onCreateView(MainFragment.java:72)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2074)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:619)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1239)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.app.Activity.performStart(Activity.java:6057)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2394)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:154)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.os.Looper.loop(Looper.java:135)
08-07 01:49:38.304 25153-25153/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5276)
08-07 01:49:38.304 25153-25153/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-07 01:49:38.304 25153-25153/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
08-07 01:49:38.304 25153-25153/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
08-07 01:49:38.304 25153-25153/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

**Comment by GIGAMOLE** [comment]
Hello. Thanks for feedback.
I`ll try to fix this. 
Wait for update.

**Comment by GIGAMOLE** [comment]
Update 1.0.4 is on the rails.
