### ISSUE TITLE
how do i put fragments in 

### ISSUE THREAD

**Issue by kevinkwabena** [DevLight-Mobile-Agency/NavigationTabStrip#2]

**Comment by GIGAMOLE** [comment]
Hello. Please describe your question.

**Comment by kevinkwabena** [comment]
i want to add fragments to the navigation tab strip like dis
![68747470733a2f2f6431337961637572716a676172612e636c6f756466726f6e742e6e65742f75736572732f3235393533382f73637265656e73686f74732f323539343130372f746162732d7472616e736974696f6e2e676966](https://cloud.githubusercontent.com/assets/2401204/15400072/b34afa3c-1dd9-11e6-85c0-04866a65e220.gif)

**Comment by GIGAMOLE** [comment]
In sample app you can see how i do this. In NTS you can set ViewPager and get effect like this. Thanks.
