### ISSUE TITLE
How to change the size of the pointer used in between the strip

### ISSUE THREAD

**Issue by Ritesh91** [DevLight-Mobile-Agency/NavigationTabStrip#21]
I am using the library in my project but unable to change the pointer size in the between the tab strip.
Please let me know how can I do that

**Comment by GIGAMOLE** [comment]
Hello. Thanks for issue.
Just use nts_weight attribute.

**Comment by Ritesh91** [comment]
using nts_weight is changing it to square, I want it to be perfect circle

**Comment by GIGAMOLE** [comment]
app:nts_type="point"

**Comment by Ritesh91** [comment]
I have used the same, still it changed to square
![screenshot_20160916-132743](https://cloud.githubusercontent.com/assets/16797267/18579171/95ded1bc-7c11-11e6-8a6a-5bc12e14c57c.jpg)

**Comment by GIGAMOLE** [comment]
app:nts_corners_radius="the half of your weight"

**Comment by Ritesh91** [comment]
How to get the pointer in exact center of the strip
![screenshot_20160916-133404](https://cloud.githubusercontent.com/assets/16797267/18579277/5f9ae48c-7c12-11e6-97d8-7a97821d3713.jpg)

**Comment by GIGAMOLE** [comment]
This is doing by your own way. Change margin top in your layout.

**Comment by Ritesh91** [comment]
Thanks a lot for your help
![screenshot_20160916-133404](https://cloud.githubusercontent.com/assets/16797267/18579432/3d3026e0-7c13-11e6-81b5-51fa34aa7b4e.jpg)

**Comment by Ritesh91** [comment]
![screenshot_20160916-134033](https://cloud.githubusercontent.com/assets/16797267/18579447/5037f2ae-7c13-11e6-92fa-d888ca6f8f52.jpg)

**Comment by Ritesh91** [comment]
hey do you mind if I ask you something else 
My email : ragrawal91@gmail.com
skype : nm.ritesh

**Comment by GIGAMOLE** [comment]
Yes. Sure.

**Comment by Ritesh91** [comment]
Hi,

I have one animation module which I am working on would you like to help on
that
Skype : nm.ritesh

**Comment by GIGAMOLE** [comment]
Contact to me.

**Comment by Ritesh91** [comment]
Please share your email id or skype

**Comment by GIGAMOLE** [comment]
gigamole53@gmail.com
