### ISSUE TITLE
ALLCAPS False

### ISSUE THREAD

**Issue by mohammedelnady** [DevLight-Mobile-Agency/NavigationTabStrip#60]
ALLCAPS False

**Comment by EpicNav** [comment]
Hey mate, I have fixed the issue of AllCaps,
Just download the file and add it to your project and make sure to change the package name in the file after it's imported.
and then use it in Layout. Should work perfectly.


nts_allCaps="false"
nts_allCaps="true"

by default it's set to false

[Download Fix](https://drive.google.com/file/d/1sNkiWZIz1h9RUTSoVgulBEkbygxHwUAZ/view?usp=sharing)

**Comment by mohamedelandy** [comment]
thanks for rapid reply, bro you save me time
